### ISSUE TITLE
Is the Spanish name of our group "Código Para Miami"?

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/es.codeformiami.org#10]
Or is it still "Code for Miami?" I always have been confused about these things. Similarly, the Spanish name for Code for America is "Code for America," right? @rebekahmonson, you're a journalist. What's the style guide say?

**Comment by herrdragon** [comment]
Well, do you need to translate the name?  Usually names are not translated, but if you want to say "Code for Miami" in spanish, it is "Código para Miami"

Miguel Herrnsdorf

Date: Tue, 10 Jun 2014 07:51:18 -0700

**Comment by CristinaSolana** [comment]
The convention is to not translate the name.
